SCR_MissionHeader {
 World "{CD6445F41F00FFD9}worlds/ESC_EscapeDebug/ESC_EscapeDebug.ent"
 SystemsConfig "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf"
 m_sName "The Escape - Eden USxUSSR"
 m_sAuthor "TheDoctor"
 m_sPath "Missions/ESC_Escape_Eden_US_USSR.conf"
 m_sDescription "Escaping from Eden"
 m_sDetails "Move to the extraction point to get out of the island."
 m_sGameMode "Escape"
 m_iPlayerCount 32
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 100
}